object Version {
    const val CORE = "1.8.0"
    const val APPCOMPAT = "1.5.0"
    const val MATERIAL = "1.6.1"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val JUNIT = "4.13.2"
    const val ANDROID_JUNIT = "1.1.3"
    const val ESPRESSO_CORE = "3.4.0"
    const val HILT = "2.42"
    const val KTX = "1.5.1"
    const val RETROFIT = "2.9.0"
    const val OKHTTP = "4.10.0"
    const val TIMBER = "5.0.1"
    const val COROUTINES = "1.6.4"
    const val DATASTORE = "1.0.0"
    const val MOCKK = "1.11.0"
    const val JUPITER = "5.9.1"
    const val ASSERTJ = "3.11.1"
    const val PAGING = "3.1.1"
}
